// Example: register a bundle id, sign a distribution certificate
// from a local CSR, and mint an App Store provisioning profile tying
// them together.
package main

import (
	"context"
	"encoding/base64"
	"errors"
	"log"
	"os"
	"time"

	Apple "github.com/godrealms/go-apple-sdk"
	AppStoreConnect "github.com/godrealms/go-apple-sdk/app-store-connect"
)

func main() {
	kid := ""
	iss := ""
	bid := ""
	privateKey := ""

	// Local path to a CSR generated by openssl req -new -keyout key.pem ...
	csrPath := "./acme.csr"

	client := Apple.NewClient(false, kid, iss, bid, privateKey)
	svc := client.AppStoreConnect()

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	// 1. Register the Bundle ID. Apple refuses duplicates, so a
	//    production caller should first List/filter to skip this step
	//    if the identifier already exists.
	bundle, err := svc.BundleIDs().Create(ctx, AppStoreConnect.CreateBundleIDRequest{
		Identifier: "com.acme.widgets",
		Name:       "Acme Widgets",
		Platform:   "IOS",
	})
	if err != nil {
		fatal("create bundle id", err)
	}
	log.Printf("bundle id registered: %s", bundle.Id)

	// 2. Sign a distribution certificate. Apple expects the CSR
	//    already base64-encoded; the raw .csr file is PEM text.
	csrBytes, err := os.ReadFile(csrPath)
	if err != nil {
		log.Fatalf("read CSR: %v", err)
	}
	cert, err := svc.Certificates().Create(ctx, AppStoreConnect.CreateCertificateRequest{
		CSRContent:      base64.StdEncoding.EncodeToString(csrBytes),
		CertificateType: "IOS_DISTRIBUTION",
	})
	if err != nil {
		fatal("create certificate", err)
	}
	log.Printf("certificate minted: %s (expires %s)", cert.Id, cert.Attributes.ExpirationDate)

	// 3. Mint an App Store provisioning profile tying the two together.
	profile, err := svc.Profiles().Create(ctx, AppStoreConnect.CreateProfileRequest{
		Name:           "Acme Widgets App Store",
		ProfileType:    "IOS_APP_STORE",
		BundleID:       bundle.Id,
		CertificateIDs: []string{cert.Id},
	})
	if err != nil {
		fatal("create profile", err)
	}
	log.Printf("profile created: %s (uuid %s)", profile.Id, profile.Attributes.UUID)

	// The profile content ships back as base64 — decode and write
	// it to disk so Xcode can consume it directly.
	if profile.Attributes.ProfileContent != "" {
		raw, err := base64.StdEncoding.DecodeString(profile.Attributes.ProfileContent)
		if err != nil {
			log.Fatalf("decode profile content: %v", err)
		}
		if err := os.WriteFile("acme-app-store.mobileprovision", raw, 0o644); err != nil {
			log.Fatalf("write profile: %v", err)
		}
		log.Printf("wrote acme-app-store.mobileprovision (%d bytes)", len(raw))
	}
}

func fatal(label string, err error) {
	var apiErr *AppStoreConnect.APIError
	if errors.As(err, &apiErr) {
		log.Fatalf("%s: Apple rejected the request: HTTP %d, %d errors", label, apiErr.StatusCode, len(apiErr.Errors))
	}
	log.Fatalf("%s: %v", label, err)
}
